export { AddProductPage } from './AddProductPage'
export { AddToCart } from './AddToCart'
export { AllProductsPage } from './AllProductsPage'
export { EditProductPage } from './EditProductPage'
export { LoginPage } from './LoginPage'
export { ShowProductPage } from './ShowProductPage'
export { Register } from './Register'
